### ISSUE TITLE
[JOSS Review] Error in `tutorial_textmodule.ipynb` - supervised classification

### ISSUE THREAD

**Issue by FlorianK13** [sandialabs/pvOps#50]
When running the following cell I get an error.

# Cell:
```python
# Setting few cross validation splits because of few example data
results, best_model = e.classify_supervised(n_cv_splits=2, embedding='tfidf')
print('best_model', best_model)
results
```

# Error: 
UnboundLocalError: local variable 'results_df' referenced before assignment
ValueError: Invalid parameter 'normalize' for estimator RidgeClassifier(alpha=0.0). Valid parameters are: ['alpha', 'class_weight', 'copy_X', 'fit_intercept', 'max_iter', 'positive', 'random_state', 'solver', 'tol'].

Since there is some ML happening in the background it might also be related to my PC? Can you reproduce this error?

**Comment by kbonney** [comment]
I can reproduce this on my end. Not sure what is going on here, but I'll be digging into things...

**Comment by MichaelHopwood** [comment]
@kbonney it seems y'all may have updated scikit-learn and now the RidgeClassifier is not supported.  We do not have pytests for example code, so that's why it must have passed the build. 

The fix is to remove this line: https://github.com/sandialabs/pvOps/blob/01be577e510ec4c564ea48df3d695b65eee537d5/pvops/text/defaults.py#L98

**Comment by kbonney** [comment]
Addressed in https://github.com/sandialabs/pvOps/pull/83
