### ISSUE TITLE
Deep copy needed before each scaling in predict_subset() method of pvops/timeseries/models/AIT.py

### ISSUE THREAD

**Issue by agmoore4** [sandialabs/pvOps#98]
Currently, when new standardized columns are created, the original columns are also standardized. This results in the R2 and logRMSE being calculated between the predicted unscaled energy and the true scaled energy, suggesting (incorrectly) that the model performs poorly.

There is a deep copy at the start of the method, but it doesn't do anything. The deep copy needs to happen inside the for-loop before each standardization is applied.

**Comment by kbonney** [comment]
This probably worked correctly at some point, but pandas is always messing with how data accessing and copying work with DataFrames. IMO we really should be using numpy arrays instead of  pandas DataFrames for the internals of the ML here, since arrays have much more stable behavior for situations like this.
